aboutus/urls.py
from django.urls import path
from . import views



app_name = 'aboutus'

urlpatterns = [
    path('', views.aboutus_list, name='aboutus_list'),
]

blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'

urlpatterns = [
    path('',views.post_list , name='post_list' ),
    path('<int:id>' , views.post_detail , name='post_detail'),
    path('tags=<slug:tag>' , views.post_by_tag , name='post_by_tag'),
    path('category=<slug:category>' , views.post_by_category , name='post_by_category'),
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home'

urlpatterns = [
    path('',views.home , name='home' ),
]

meals/urls.py
from django.urls import path
from . import views



app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail'),
]

aboutus/models.py
from django.db import models

# Create your models here.

class AboutUs(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='aboutus/', null=True)

    class Meta:
        verbose_name = 'about us'
        verbose_name_plural = 'about us'

    def __str__(self) -> str:
        return self.title


class WhyChooseUs(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    class Meta:
        verbose_name = 'why choose us'
        verbose_name_plural = 'why choose us'

    def __str__(self) -> str:
        return self.title


class Chef(models.Model):
    name = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    bio = models.TextField()
    image = models.ImageField(upload_to='chef/')

    class Meta:
        verbose_name = 'chef'
        verbose_name_plural = 'chefs'

    def __str__(self) -> str:
        return self.name

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

class Post(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog/', blank=True, null=True)
    tags = TaggableManager(blank=True)
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self) -> str:
        return self.title

class Category(models.Model):
    category_name = models.CharField(max_length=70)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.category_name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self) -> str:
        return self.content

home/models.py
from django.db import models

# Create your models here.

meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Meal(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)


    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meal, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    def __str__(self) -> str:
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name

blog/forms.py
from django import forms
from django.db.models import fields
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]

aboutus/views.py
from django.shortcuts import render
from .models import AboutUs, WhyChooseUs, Chef


def aboutus_list(request):
    about = AboutUs.objects.last()
    why_choose_us = WhyChooseUs.objects.all()
    chef = Chef.objects.all()

    context = {
        'about' : about ,
        'why_choose_us' : why_choose_us ,
        'chef' : chef,
    }

    return render(request , 'about.html' , context)

blog/views.py
from django.shortcuts import render
from .models import Post , Category , Comment
from taggit.models import Tag
from .forms import CommentForm
from django.core.paginator import Paginator
from django.db.models import Q
# Create your views here.


def post_list(request):
    post_list = Post.objects.all()

    ## search
    search_query = request.GET.get('q')
    if search_query :
        post_list = post_list.filter(
            Q(title__icontains = search_query)|
            Q(content__icontains= search_query) |
            Q(tags__name__icontains= search_query)
        ).distinct()

    paginator = Paginator(post_list, 2) # Show 25 posts per page

    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {
        'post_list' : post_list ,
    }

    return render(request , 'post_list.html' , context)


def post_detail(request , id):
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post_detail)


    if request.method == 'POST' :
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_detail
            new_comment.save()

    else:
        comment_form = CommentForm()

    context = {
        'post_detail' : post_detail ,
        'categories' : categories ,
        'all_tags' : all_tags ,
        'comments' : comments ,
        'comment_form' : comment_form
    }

    return render(request , 'post_detail.html' , context)




def post_by_tag(request , tag):
    post_by_tag = Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list' : post_by_tag ,
    }

    return render(request , 'post_list.html' , context)





def post_by_category(request , category):
    post_by_category = Post.objects.filter(category__category_name=category)
    context = {
        'post_list' : post_by_category ,
    }

    return render(request , 'post_list.html' , context)

home/views.py
from django.shortcuts import render
from meals.models import Meal , Category
from blog.models import Post
from aboutus.models import WhyChooseUs


def home(request):

    meals = Meal.objects.all()
    meal_list = Meal.objects.all()
    categories = Category.objects.all()
    posts = Post.objects.all()
    latest_post = Post.objects.last()
    why_choose_us = WhyChooseUs.objects.all()



    context = {
        'meals' : meals ,
        'meal_list' : meal_list ,
        'categories' : categories ,
        'posts' : posts ,
        'latest_post' : latest_post ,
        'why_choose_us' : why_choose_us ,
    }

    return render(request , 'index.html' , context)

meals/views.py
from django.shortcuts import render

from .models import Meal, Category

# Create your views here.

def meal_list(request):
    meal_list = Meal.objects.all()
    categories = Category.objects.all()
    context = {
        'meal_list': meal_list,
        'categories': categories,
        }
    return render(request, 'meals/list.html', context)

def meal_detail(request, slug):
    meal_detail = Meal.objects.get(slug=slug)

    context = {'meal_detail' : meal_detail}
    return render(request, 'meals/detail.html', context=context)

aboutus/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">About The Restaurant</h2>
                  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo saepe dolorum dolorem, iste officia voluptates! Sint repudiandae, soluta voluptatem delectus iure, eaque, harum expedita, nisi aliquam magni odio perferendis ipsum!</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        <div class="section">
          <div class="container">
            <div class="row">
              <div class="col-md-7" data-aos="fade-up">
                <img src="{% static 'img/about_1.png' %}" alt="Image placeholder" class="img-fluid">
              </div>
              <div class="col-md-5 pl-md-5" data-aos="fade-up" data-aos-delay="200">
                <h2 class="mb-4">{{about.title}}</h2>
                <p>{{about.content}}</p>

              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Why Choose Us</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row large-gutters">
              <div class="col-md-6"  data-aos="fade-up" data-aos-delay="200">
                <img src="{% static 'img/img_2.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                <div class="accordion" id="accordion">
                  {% for info in why_choose_us %}

                    <div class="accordion-item">
                      <h3 class="mb-0">
                        <a class="btn-block p-3" data-toggle="collapse" href="#collapse{{info.id}}" role="button" aria-expanded="true" aria-controls="collapseOne">{{info.title}} <span class="icon"></span></a>
                      </h3>
                      <div id="collapse{{info.id}}" class="collapse " aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="p-3">
                          <p>{{info.content}}</p>
                        </div>
                      </div>
                    </div> <!-- .accordion-item -->

                  {% endfor %}

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Restaurants Chef</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row">
              {% for one in chef %}

                <div class="col-md-3" data-aos="fade-up" data-aos-delay="100">
                  <img src="{{one.image.url}}" alt="Image placeholder" class="img-fluid mb-4 rounded">
                  <h3 class="mb-3">{{one.name}}</h3>
                  <p class="post-meta text-muted">{{one.title}}</p>
                  <p class="mb-5">{{one.bio}}</p>
                </div>

              {% endfor %}
            </div>
          </div>
        </div> <!-- .section -->

      </div> <!-- .main-wrap -->

      {% endblock body %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}



      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                  <h2 class="heading mb-4">{{post_detail}}</h2>

                  <div class="post-info">
                    <div class="date-info">{{post_detail.created}}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">{{post_detail.category}}</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">{{post_detail.author}}</a></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">

            <div class="row">

              <div class="col-md-8">
                <h1 class="text_center">{{post_detail.title}}</h1>
                <img class="img-fluid" src="{{ post_detail.image.url }}" alt="image of {{post_detail.title}}">
                <p>{{post_detail.content}}</p>

                <div class="tag-widget post-tag-container mb-5 mt-5">
                  <div class="tagcloud">

                    {% for tag in post_detail.tags.all %}
                        <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag.name}}</a>
                    {% endfor %}
                  </div>
                </div>


                <div class="pt-5 mt-5">
                  <h3 class="mb-5"> Comments</h3>
                  <ul class="comment-list">

                    {% for comment in comments %}
                      <li class="comment">
                        <div class="vcard bio">
                          <img src="{% static 'img/person_1.jpg' %}" alt="Image placeholder">
                        </div>
                        <div class="comment-body">
                          <h3>{{comment.user}}</h3>
                          <div class="meta">{{comment.created}}</div>
                          <p>{{comment.content}}</p>
                        </div>



                      </li>
                    {% endfor %}
                  </ul>
                  <!-- END comment-list -->

                  <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5">Leave a comment</h3>
                    <form method="POST" class="p-5 bg-light">
                        {% csrf_token %}
                        {% bootstrap_form comment_form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Leave A Comment</button>
                        {% endbuttons %}
                    </form>
                  </div>
                </div>

              </div> <!-- .col-md-8 -->
              <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                  <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                    <div class="form-group">
                      <span class="icon fa fa-search"></span>
                      <input type="text" class="form-control" name="q" value="{{request.Get.q}}" placeholder="Type a keyword and hit enter">
                    </div>
                  </form>
                </div>
                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories</h3>
                    {% for category in categories %}
                    <li><a href="{% url 'blog:post_by_category' category %}">{{category}}</a></li>

                    {% endfor %}
                  </div>
                </div>


                <div class="sidebar-box">
                  <h3>Tag Cloud</h3>
                  <div class="tagcloud">

                      {% for tag in all_tags %}
                        <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
                      {% endfor %}
                  </div>
                </div>


              </div>

            </div>


          </div>
        </div> <!-- .section -->



      </div> <!-- .main-wrap -->

      {% endblock body %}

blog/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    
    
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Blog Grid</h2>
                  <p class="lead">All is well</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">
            
            <div class="row mb-5">
             {% for post in post_list %}
              
                <div class="col-md-4">
                    <div class="media d-block media-bg-white mb-5" data-aos="fade-up"  data-aos-delay="400">
                    <figure>
                        <a href="{% url 'blog:post_detail' post.id %}"><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                    </figure>
                    <div class="media-body">
                        <h3><a href="{% url 'blog:post_detail' post.id %}">{{post}}</a></h3>
                        <p class="post-meta"><span><span class="fa fa-calendar"></span> {{post.created}}</span></p>
                        <p class="mb-4">{{post.content|truncatewords:20}}</p>
                        <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                    </div>
                    </div> <!-- .media -->
                </div>
             {% endfor %}
            </div>

            <div class="row">

              {% if post_list.has_other_pages %}

                <div class="col-md-12">
                  <ul class="pagination custom-pagination">
                    {% if post_list.has_previous %}
                      <li class="page-item prev"><a class="page-link" href="?page={{post_list.previous_page_number}}"><i class="fa fa-angle-left"></i></a></li>
                    {% else %}
                      <li class="disabled"></li>
                    {% endif %}

                    {% for pages in post_list.paginator.page_range %}
                      {% if post_list.number == pages %}
                        <li class="page-item active"><a class="page-linkx" href="#">{{pages}}</a></li>
                      {% else %}
                        <li class="page-item active"><a class="page-linkx" href="?page={{pages}}">{{pages}}</a></li>
                      {% endif %}

                    {% endfor %}


                    {% if post_list.has_next %}
                      <li class="page-item next"><a class="page-link" href="?page={{post_list.next_page_number}}"><i class="fa fa-angle-right"></i></a></li>
                    {% else %}
                      <li class="disabled"></li>
                    {% endif %}
                  </ul>


                </div>
              {% endif %}
            </div>
        </div> <!-- .section -->



      </div> <!-- .main-wrap -->
      
      {% endblock body %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
  

  
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %})" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        <div class="section services-section">
          <div class="container">
             
            <div class="row">
              <div class="col-md-6 col-lg-3" data-aos="fade-up">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-soup"></span>
                  </div>
                  <div class="media-body">
                    <h3>Quality Cuisine</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non pariatur suscipit repudiandae facilis incidunt unde saepe</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="100">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-vegetables"></span>
                  </div>
                  <div class="media-body">
                    <h3>Fresh Food</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non pariatur suscipit repudiandae facilis incidunt unde saepe</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="300">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-pancake"></span>
                  </div>
                  <div class="media-body">
                    <h3>Friendly Staff</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non pariatur suscipit repudiandae facilis incidunt unde saepe</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="500">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-tray"></span>
                  </div>
                  <div class="media-body">
                    <h3>Easy Reservation</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non pariatur suscipit repudiandae facilis incidunt unde saepe</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Our Specialties</h2>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae eum voluptatem odio expedita laborum fugit repudiandae dolorem consectetur.</p>
              </div>
            </div>
          </div>
        </div> <!-- .section -->
        
        <div class="section pt-0 pb-0">

          <div class="menus d-flex bg-light">

            {% for meal in meals %}
              
            <div class="d-flex item">
              <div class="image" style="background-image: url({{meal.image.url}});" data-aos="fade"></div>
              <div class="text">
                <h3>{{meal.name}}</h3>
                <p>{{meal.description|truncatewords:15}}</p>
                <p class="price">${{meal.price}}</p>
              </div>
            </div> <!-- .item -->

            {% endfor %}

          </div>
        </div> <!-- .section -->



        <div class="section">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-8" data-aos="fade-up">
  
                  <h2 class="mb-5 text-center">Menu List with Price</h2>
  
                  <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                    {% for category in categories %}
                      <li class="nav-item">
                        <a class="nav-link " id="{{category}}-tab" data-toggle="pill" href="#{{category}}" role="tab" aria-controls="{{category}}" aria-selected="true">{{category}}</a>
                      </li>
                    {% endfor %}
  
                  </ul>
  
  
                  <div class="tab-content" id="pills-tabContent">
  
                    {% for category in categories %}
  
                      <div class="tab-pane fade show" id="{{category}}" role="tabpanel" aria-labelledby="{{category}}-tab">

                        {% for meal in meal_list %}
                            {% if meal.category == category%}
                              <div class="d-block d-md-flex menu-food-item">
                                <div class="text order-1 mb-3">
                                  <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h3>
                                  <p>{{meal.description|truncatewords:20}}</p>
                                </div>
                                <div class="price order-2">
                                  <strong>${{meal.price}}</strong>
                                </div>
                              </div> <!-- .menu-food-item -->
                            {% endif %}
                        {% endfor %}
  
                      </div>
                      
                    {% endfor %}
                  </div>
  
  
                </div>
              </div>
            </div>
          </div>

        <div class="section bg-light">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Events &amp; News</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">

               {% for post in posts %}
                 
              
                <div class="media d-block d-lg-flex mb-5"  data-aos="fade-up" data-aos-delay="100">
                  <figure class="mr-4 horizontal">
                    <img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid">
                  </figure>
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span> {{post.created}}</span></p>
                    <p>{{post.content|truncatewords:10}}</p>
                    <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->
                {% endfor %} 


              </div> <!-- .col-md-6 -->

              <div class="col-lg-6">
                <div class="media d-block mb-5" data-aos="fade-up"  data-aos-delay="400">
                  <figure>
                    <a href="#"><img src="{{latest_post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' latest_post.id %}>" {{latest_post.title}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span> April 22, 2018</span></p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto illo delectus</p>
                    <p><a href="{% url 'blog:post_detail' latest_post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
            <div class="container">
              <div class="row justify-content-center mb-5" data-aos="fade-up">
                <div class="col-md-8  text-center">
                  <h2 class="mb-3">Why Choose Us</h2>
                  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
                </div>
              </div>
              <div class="row large-gutters">
                <div class="col-md-6"  data-aos="fade-up" data-aos-delay="200">
                  <img src="{% static 'img/img_2.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
                </div>
                <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                  <div class="accordion" id="accordion">
                    {% for info in why_choose_us %}

                      <div class="accordion-item">
                        <h3 class="mb-0">
                          <a class="btn-block p-3" data-toggle="collapse" href="#collapse{{info.id}}" role="button" aria-expanded="true" aria-controls="collapseOne">{{info.title}} <span class="icon"></span></a>
                        </h3>
                        <div id="collapse{{info.id}}" class="collapse " aria-labelledby="headingOne" data-parent="#accordion">
                          <div class="p-3">
                            <p>{{info.content}}</p>
                          </div>
                        </div>
                      </div> <!-- .accordion-item -->
  
                    {% endfor %}
  
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- .section -->


      </div> <!-- .main-wrap -->
      {% endblock body %}